#Tomcat Server
server:
  port: 8081
  error.include-stacktrace: always 

#Logger
logging.level:
  debug: DEBUG
  '[com.javaprojects.springcrud]': ERROR
  # Can be DEBUG for Development
  # Can be ERROR after Development
  # Can be OFF to turn the logger statemts off

#Database Setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_projects
    username: root
    password: root1
    